# Generated by Django 5.2.6 on 2025-10-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('accessories', 'Accessories'), ('jerseys', 'Jerseys'), ('boots', 'Boots'), ('clothing', 'Clothing'), ('street wear', 'Street Wear')], max_length=20),
        ),
    ]
