# Generated by Django 5.2.6 on 2025-09-17 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_created_at_product_is_product_hot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_product_hot',
        ),
    ]
